/** @type {import("../../../../assembler/src/template.js").GenPart} */
module.exports = (schema) => ({
  "terminal.foreground": schema.ui.text,
  "terminal.background": schema.terminal.background,
  // "terminal.border": "#F0F",
  // "terminal.dropBackground": "#F0F",
  // "terminal.tab.activeBoarder": "#F0F",
  "terminal.selectionBackground": schema.terminal.selection,
  "terminalCursor.background": schema.terminal.selection,
  "terminalCursor.foreground": schema.ui.text,
  "terminal.ansiBlack": schema.terminal.black,
  "terminal.ansiBrightBlack": schema.terminal.blackBright,
  "terminal.ansiBlue": schema.terminal.blue,
  "terminal.ansiBrightBlue": schema.terminal.blueBright,
  "terminal.ansiCyan": schema.terminal.cyan,
  "terminal.ansiBrightCyan": schema.terminal.cyanBright,
  "terminal.ansiGreen": schema.terminal.green,
  "terminal.ansiBrightGreen": schema.terminal.greenBright,
  "terminal.ansiMagenta": schema.terminal.magenta,
  "terminal.ansiBrightMagenta": schema.terminal.magentaBright,
  "terminal.ansiRed": schema.terminal.red,
  "terminal.ansiBrightRed": schema.terminal.redBright,
  "terminal.ansiWhite": schema.terminal.white,
  "terminal.ansiBrightWhite": schema.terminal.whiteBright,
  "terminal.ansiYellow": schema.terminal.yellow,
  "terminal.ansiBrightYellow": schema.terminal.yellowBright,
});
