const staticTokens = require("./tokens/__static.js");
const typeTokens = require("./tokens/__types.js");
const operatorTokens = require("./tokens/__operators.js");
const languageTokens = require("./tokens/__language.js");
const literalTokens = require("./tokens/__literals.js");
const markdownTokens = require("./tokens/__markdown.js");
const keyLevels = require("./tokens/__key_levels.js");
const regexpTokens = require("./tokens/__regexp.js");

const terminalColors = require("./ui/__terminal.js");

/** @type {import('../../../assembler/src/template').GenPack} */
module.exports = (schemas) => {
  return schemas.map((schema) => {
    const ui = { ...schema.ui, ...schema.vscode };

    return [
      `${schema.id}.json`,
      {
        $schema: "vscode://schemas/color-theme",
        name: schema.name,
        type: schema.lightness,
        semanticHighlighting: true,
        semanticTokenColors: {
          class: schema.tokens.types.class,
          enum: schema.tokens.types.enum,
          function: schema.tokens.types.function,
          interface: schema.tokens.types.interface,
          namespace: schema.tokens.types.namespace,
          struct: schema.tokens.types.struct,
          type: schema.tokens.types.type,
          variable: schema.tokens.language.variable,
          "variable.defaultLibrary": schema.tokens.language.builtin,
        },
        tokenColors: [
          // TODO git_gutter
          // TODO regex highlight
          // TODO this | self
          // TODO string template parenthesis (test1: html.js vs js.html)
          // TODO samples for `*.{css,sass,scss,less,stylus,postcss}`
          // TODO samples for all tested languages
          ...staticTokens,
          ...typeTokens(schema),
          ...operatorTokens(schema),
          ...languageTokens(schema),
          ...literalTokens(schema),
          ...markdownTokens(schema),
          ...keyLevels("JSON", schema.tokens.keyLevels, {
            source: "json",
            repeat: "meta.structure.dictionary",
            end: "support.type.property-name",
            levels: 50,
          }),
          ...keyLevels("JS/TS Object Literal", schema.tokens.keyLevels, {
            // TODO `{[<keyvar>]: {}}` conflict with semantic.variable
            source: "js|ts",
            repeat: "meta.objectliteral meta.object.member",
            end: [
              "meta.object-literal.key",
              "meta.object-literal.key string",
              "variable",
            ], // variable, quoted string or not,
            levels: 16,
          }),
          ...keyLevels("SCSS Map", schema.tokens.keyLevels, {
            // TODO string value has the wrong color
            source: "scss|css.scss",
            repeat: "meta.definition.variable.map",
            end: ["string.quoted", "support.type.map.key"],
            levels: 16,
          }),
          // TODO tokenize keylevels: py,php,c#,dart,yaml,go
          // TODO tokenize proplevels: js,ts
          // TODO more realistic keylevel test
          ...regexpTokens(schema),
        ],
        colors: {
          ...terminalColors(schema),
          
          "activityBar.background": ui.iconbar.background,
          "editor.background": ui.editor.background,
          "editorIndentGuide.background": ui.indentGuide.inactive,
          "editorIndentGuide.activeBackground": ui.indentGuide.active,
          "editorGroupHeader.tabsBackground": ui.tab.empty.background,
          "editorGutter.addedBackground": ui.gitStatus.added.background,
          "editorGutter.modifiedBackground": ui.gitStatus.modified.background,
          "editorGutter.deletedBackground": ui.gitStatus.deleted.background,
          "editorWidget.background": ui.docbox.background,
          focusBorder: ui.focusBorder,
          "minimap.background": ui.minimap.background,
          "panel.background": ui.panel.background,
          "panelTitle.activeBorder": ui.panel.marker,
          "sideBar.background": ui.sidebar.background,
          "sideBarSectionHeader.background": ui.sidebar.header.background,
          "statusBar.background": ui.statusbar.default,
          "statusBar.noFolderBackground": ui.statusbar.default,
          "statusBar.border": ui.statusbar.border,
          "statusBar.debuggingBackground": ui.statusbar.debug,
          "tab.activeBackground": ui.tab.active.background,
          "tab.activeBorder": ui.tab.active.marker,
          "tab.inactiveBackground": ui.tab.inactive.background,
          "tab.unfocusedActiveBorder": ui.tab.unfocused.border,
          "titleBar.activeBackground": ui.titlebar.active.background,
          "titleBar.inactiveBackground": ui.titlebar.inactive.background,

          "textBlockQuote.background": "#24292e",
          "peekViewResult.background": "#1f2428",
          "dropdown.listBackground": "#24292e",
          "notificationCenterHeader.background": "#24292e",
          "quickInput.background": "#24292e",
          "tab.hoverBackground": "#24292e",
          "tab.unfocusedHoverBackground": "#24292e",

          "dropdown.border": "#0000",
          "input.border": "#0000",
          "editorOverviewRuler.border": "#0000",
          "checkbox.border": "#0000",
          "titleBar.border": "#0000",
          "activityBar.border": "#0000",
          "sideBar.border": "#0000",
          "sideBarSectionHeader.border": "#0000",
          "notifications.border": "#0000",
          "editorGroupHeader.tabsBorder": "#0000",
          "editorGroup.border": "#0000",
          "tab.border": "#0000",
          "tab.unfocusedActiveBorderTop": "#0000",
          "panel.border": "#0000",

          foreground: "#d1d5da",
          descriptionForeground: "#959da5",
          errorForeground: "#f07178",
          "textLink.foreground": "#8389E7",
          "textLink.activeForeground": "#c8e1ff",
          "textBlockQuote.border": "#444d56",
          "textCodeBlock.background": "#2f363d",
          "textPreformat.foreground": "#d1d5da",
          "textSeparator.foreground": "#586069",
          "button.background": "#176f2c",
          "button.foreground": "#dcffe4",
          "button.hoverBackground": "#22863a",
          "dropdown.background": "#2f363d",
          "dropdown.foreground": "#e1e4e8",
          "input.background": "#2f363d",
          "input.foreground": "#e1e4e8",
          "input.placeholderForeground": "#959da5",
          "badge.foreground": "#c8e1ff",
          "badge.background": "#044289",
          "progressBar.background": "#0366d6",
          "list.hoverForeground": "#e1e4e8",
          "list.activeSelectionForeground": "#e1e4e8",
          "list.hoverBackground": "#282e34",
          "list.inactiveSelectionBackground": "#282e34",
          "list.activeSelectionBackground": "#39414a",
          "list.inactiveFocusBackground": "#1d2d3e",
          "list.focusBackground": "#044289",
          "pickerGroup.border": "#444d56",
          "pickerGroup.foreground": "#e1e4e8",
          "editor.foreground": "#e1e4e8",
          "editor.lineHighlightBackground": "#2b3036",
          "editorLineNumber.foreground": "#444d56",
          "editorWhitespace.foreground": "#444d56",
          "editorCursor.foreground": "#c8e1ff",
          "editor.findMatchBackground": "#ffd33d44",
          "editor.findMatchHighlightBackground": "#ffd33d22",
          "editor.inactiveSelectionBackground": "#3392FF22",
          "editor.selectionBackground": "#3392FF44",
          "editor.selectionHighlightBackground": "#17E5E633",
          "editor.wordHighlightBackground": "#17E5E600",
          "editor.wordHighlightStrongBackground": "#17E5E600",
          "editorBracketMatch.background": "#17E5E650",
          "editorBracketMatch.border": "#17E5E600",
          "diffEditor.insertedTextBackground": "#28a74530",
          "diffEditor.removedTextBackground": "#d73a4930",
          "scrollbar.shadow": "#0008",
          "scrollbarSlider.background": "#6A737D33",
          "scrollbarSlider.hoverBackground": "#6A737D44",
          "scrollbarSlider.activeBackground": "#6A737D88",
          "peekViewEditor.matchHighlightBackground": "#ffd33d33",
          "peekViewResult.matchHighlightBackground": "#ffd33d33",
          "checkbox.background": "#444d56",
          "titleBar.activeForeground": "#e1e4e8",
          "titleBar.inactiveForeground": "#959da5",
          "activityBar.foreground": "#e1e4e8",
          "activityBar.inactiveForeground": "#6A737D",
          "activityBarBadge.foreground": "#fff",
          "activityBarBadge.background": "#0366d6",
          "activityBar.activeBorder": "#f9826c",
          "sideBar.foreground": "#d1d5da",
          "sideBarTitle.foreground": "#e1e4e8",
          "sideBarSectionHeader.foreground": "#e1e4e8",
          "list.inactiveSelectionForeground": "#e1e4e8",
          "tree.indentGuidesStroke": "#2f363d",
          "notificationCenterHeader.foreground": "#959da5",
          "notifications.foreground": "#e1e4e8",
          "notifications.background": "#2f363d",
          "notificationsErrorIcon.foreground": "#ea4a5a",
          "notificationsWarningIcon.foreground": "#ffab70",
          "notificationsInfoIcon.foreground": "#8389E7",
          "quickInput.foreground": "#e1e4e8",
          "statusBar.foreground": "#d1d5da",
          "statusBar.debuggingForeground": "#fff",
          "statusBarItem.prominentBackground": "#282e34",
          "tab.activeForeground": "#e1e4e8",
          "tab.inactiveForeground": "#959da5",
          "tab.activeBorderTop": "#f9826c",
          "breadcrumb.foreground": "#959da5",
          "breadcrumb.focusForeground": "#e1e4e8",
          "breadcrumb.activeSelectionForeground": "#d1d5da",
          "breadcrumbPicker.background": "#2b3036",
          "editor.foldBackground": "#282e33",
          "editorLineNumber.activeForeground": "#e1e4e8",
          "editor.selectionHighlightBorder": "#17E5E600",
          "editor.wordHighlightBorder": "#17E5E699",
          "editor.wordHighlightStrongBorder": "#17E5E666",
          "panelTitle.activeForeground": "#e1e4e8",
          "panelTitle.inactiveForeground": "#959da5",
          "panelInput.border": "#2f363d",
          "gitDecoration.addedResourceForeground": "#34d058",
          "gitDecoration.modifiedResourceForeground": "#8389E7",
          "gitDecoration.deletedResourceForeground": "#ea4a5a",
          "gitDecoration.untrackedResourceForeground": "#34d058",
          "gitDecoration.ignoredResourceForeground": "#6A737D",
          "gitDecoration.conflictingResourceForeground": "#ffab70",
          "gitDecoration.submoduleResourceForeground": "#6A737D",
          "debugToolBar.background": "#2b3036",
          "editor.stackFrameHighlightBackground": "#a707",
          "editor.focusedStackFrameHighlightBackground": "#b808",
          "settings.headerForeground": "#e1e4e8",
          "settings.modifiedItemIndicator": "#0366d6",
          "welcomePage.buttonBackground": "#2f363d",
          "welcomePage.buttonHoverBackground": "#444d56",
        },
      },
    ];
  });
};
